### ISSUE TITLE
RSS feeds output raw markdown

### ISSUE THREAD

**Issue by rscmbbng** [benjojo/bnblog#1]
hey, really enjoy reading the blog. I noticed however that since a few months your blog's RSS feed only outputs a few lines of unrendered markdown instead of the entire article. 

see:
`curl https://blog.benjojo.co.uk/rss.xml `

**Comment by benjojo** [comment]
It's always been this way, Ideally I want the intro paragraph to appear and get people to actually click over.

This seems selfish (and I'll give you that, it is, and slightly breaks RFC/spec) however:

Motivation to write posts (and me figuring out what people actually enjoy) is mostly done by me seeing traffic for the posts, so I actually need to have people click on them for me to write more otherwise I'll just figure it's pointless.

I'll try and at least render the markdown at least so it looks less horrendous over RSS!

**Comment by rscmbbng** [comment]
> Motivation to write posts (and me figuring out what people actually enjoy) is mostly done by me seeing traffic for the posts, so I actually need to have people click on them for me to write more otherwise I'll just figure it's pointless.

Well I get that and the fact that an RSS feed doesn't give you granular-enough info in the weblogs.  But also do know that there are people who enjoy reading your material through their reader also! Keep up the good work!
